language: python
python:
  - "3.6"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
    - pip install nose
    - pip install coverage
before_script:
  - sudo -u postgres createdb test_db
# command to run the tests
script:
  - nosetests --with-coverage
after_script:
  - sudo -u postgres dropdb test_db
