language: python
python:
  - "3.6"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
  - python -m nose --with-coverage
  - coveralls
after_success: coveralls
cache: pip
