language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests --with-coverage
after_success: coveralls
cache: pip
env:
  matrix:
  - DB=postgres
  global:
    secure: TZETRIWhSwGoYTU+xHcOkksPz3tOjwyW3x+puEls44QaW8ZgBZFfugmND4zhbD8ZwfrpvR+I6hjWfC34/2XfMH8G0WHoBc4LVdWMDmKV6OtmyWHVUwP1xcschyQW85fuq3sZ5RMeEQqCI/qBTHiIqGEMwyTRyByCgrAdtTPRwsanVoBFsvMNlwCWEYOQ5DwMuWHpcz896KZVxnEJCBYQFhsxz3Se2tO7s8+b0swZ6bEIPkL4brCYkDBYqd5cAVHvrma2lV3pVNGT3IBujQf8UV0Py5te0ZvhZuf6+lkvZtsbWdrE1VMkxm2qvSthmuyw4l0ByqEI2eIV0l8HdGv9qL1mV9cCcCcTFR9fzaXL+Dsvi/NuYkLKD5UNA3CCNnNuXTBFYE1nNlPMOhbYr/PAZMfr5yiBDj4P8pi11VkynExT5Pc1nBqtNPGS/xdhN4Y4O9Jd5XPuh/clKUYqnVFozCJ2z8EF3bhG+GWoL3Hz0ugZzTZ8WNo6FENo2mazRGTqadkoVNDiW6kTPdCdee4elr3v8TWtbBvK8xwNINe0aWpIPPbiofG7zlqxhuLwPZVRCD74iEA9jmzRQEcyZrpOls6w0hv+LYKn9VPBnsIrSBGlFBTnY0FhRl8/x0OaK9ZhV38IBsgJ8aymJjLr8VRnB5yRyDP7wtfetP/XN3nc1N4=
