language: python
python:
  - "3.6"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
# command to run the tests
script:
  - nosetests --with-coverage
after_success: coveralls
cache: pip
env:
  DB=postgres
