language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests --with-coverage
after_success: coveralls
cache: pip
env:
  matrix:
  - DB=postgres
  global:
    secure: wiqJfNrz3GcYeotW2HVE7KV5S4AVyLz82Rt8bJLZWQvWs6aYNZCcE0LPIznseXJfWqtQ7i891v4HLRBBH+UofSGUxM4epx9xqnxQrstuuhljQYWZmI1zG6G8AesFiI6cDqnCMu9dlQyfWFP5UFGXb3yuMVgYRhxdNWZQFqbYImAyGncikAlODeWodtV0+n6e1Ive8OHFBhGHxPEr15H6y09qbddPI7lC/9plY9Ii5vyGMDA+JtZyamTarLFR+3C9MWsbiz8zH0mgg4EQhfLSIWosKxBVkBRuRk0tVf+rirPiJPmpJHWKILhVtO3yk+vt7os46EErlPHELxT8e+5sonwQgcCVIFO6/R3ALUGXJjSZtKdr+ey20RHjscScOF3Kx8uu7ztYakAKcT4GQe3KnkXueKAHwsJCEGdb0Y8xt7+Dmve/Ohp//vXdSbEpBCdaLp5A6z1oSYqvmcOZ9vYZsqu0HrCIYZYxTg5vjGdIy2VIADVpTE81hCMQFc2dsv8l+8Mtb0IGX7Yqc/+o4NMeqkEBU8AX1TZo8GwIFcjR5fZtZ4uZSof2MV6I/NAlk46qg0fuOtrjwu97vchv81UubPCQazdyYYyoFJvZ3BupIK83VC+ux4Fqf3vjOT2a8ceHkMi5uJk4PpodIIGrl2dQrq6c/1uTQR7sh2ovO77ALcA=
