language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests --with-coverage
after_success: coveralls
cache: pip
env:
  matrix:
  - DB=postgres
  global:
    secure: PTP+EcdnJyH6hVFqXjnwDjoWj5AVNMlFWa8EJq+9iGiD4Dy1TBZ6mTKSK1P8PPnlqdOfGvOgjy8bNQxggzVTvQ9NVJs0Xs+JhoZ6foypHsDONpcVNaJN2ARfwvDdxdT03Agwz67CHZuhi5her3Ye/nUIhYbCdDKpZk/kdi4ej6OYv3FfkdUmphRyr8Q+YfQwbrTCBPayWvXrxc8uc7ePeVWzzJEgvklHskFZ5x/05kDMdJzkjrs+eut0UUbjJX3tzL9wJqMvpvZye0MTneS/65nMBVcxgOU7jrLi16RWrRE+56D5mBedRAPwKh5v58CsWiRlvnfhx8+273ZRHOnffviQ/ioCeTyun58DuGFRS+DWOfAfGbKep4ywSMV3ax/DXkLq0UJpHqfEZ7ktsbV/AG/A5IjkpaYduRAXxwkbJwHYkMxQyZ18AuCg+ZxUyS2wwubGHltHbTfo7xmSKwUzw2GDmncBvlhaCD1tWm0tE+tiIR9GZ2E06HNkuvha5ghsU3VNyikTcbjl+QfKfam4m5GXzMVLSJiivljjmgLDRf9wwVWDobEEsa8FiakHZDgFeIy3bPtMTSE1cOTXfw04+d0FLMhDsaU+d4HKbmh7MepA0uHWnbY/xToBZb+XUwcgFlN5PhSFvpMkeNc/U4lz7Y09aInU7OLk5KihoVjcUZw=
