"""empty message

Revision ID: 5476aace5630
Revises: e9ee8d29f8e8
Create Date: 2017-06-23 10:40:33.109794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5476aace5630'
down_revision = 'e9ee8d29f8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucketlists', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'username')
    op.alter_column('bucketlists', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
