"""empty message

Revision ID: 9dfc4aa14ead
Revises: 89bd5ed2eccf
Create Date: 2017-06-21 13:04:26.129859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfc4aa14ead'
down_revision = '89bd5ed2eccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_encrypt', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bucketlist_owner', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_owner'], ['bucketlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bucketlists', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlists', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'creator')
    op.drop_table('items')
    op.drop_table('users')
    # ### end Alembic commands ###
