"""empty message

Revision ID: e9ee8d29f8e8
Revises: fbc714892fd3
Create Date: 2017-06-21 15:40:19.942570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ee8d29f8e8'
down_revision = 'fbc714892fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'done')
    # ### end Alembic commands ###
